name: 'install libmpdata++'
description: 'installs libmpdata++, loads UWLCM Singularity image for dependencies'
inputs:
  build_type:
    description: 'CMake build type: Release, Debug, ...'
    required: true
    default: "Release"
  threads:
    description: "number of threads used by make"
    required: true
    default: 1
  path:
    description: "path to the dir with libmpdataxx code"
    required: true
  install_prefix:
    description: "CMake install prefix"
    required: true
    default: "/usr/local"
  tag:
    description: 'Singularity image tag'
    required: true
    default: 'ubuntu_20_04_cuda_11_4'
  cxx:
    description: 'C++ compiler'
    required: true
    default: 'g++'

runs:
  using: "composite"
  steps:
  - name: load UWLCM Singularity image
    uses: igfuw/load_UWLCM_singularity_image@v0.1
    with:
      path: ${{ inputs.path }}/singularity_images
      tag: ${{ inputs.tag }}
    

#  - name: Configure CMake
#    shell: bash
#    run: singularity exec $SI cmake -B ${{inputs.path}}/build -DCMAKE_BUILD_TYPE=${{inputs.build_type}} -DCMAKE_INSTALL_PREFIX=${{inputs.install_prefix}} -DCMAKE_CXX_COMPILER=${{inputs.cxx}};

#  - name: Build libmpdata++
#    shell: bash
#    run: VERBOSE=1 singularity exec $SI cmake --build ${{inputs.path}}/build --config ${{inputs.build_type}} -j${{inputs.threads}}
#
#  - name: Install libmpdata++
#    shell: bash
#    run: VERBOSE=1 singularity exec $SI cmake --install ${{inputs.path}}/build --config ${{inputs.build_type}}

  - name: configure, build and install libmpdata++
    working-directory: ${{inputs.path}}
    shell: bash
    run: VERBOSE=1 singularity exec $SI bash -c "cmake -B ${{inputs.path}}/build -DCMAKE_BUILD_TYPE=${{inputs.build_type}} -DCMAKE_INSTALL_PREFIX=${{inputs.install_prefix}} -DCMAKE_CXX_COMPILER=${{inputs.cxx}};cmake --build ${{inputs.path}}/build --config ${{inputs.build_type}} -j${{inputs.threads}};cmake --install ${{inputs.path}}/build --config ${{inputs.build_type}}"
